---
sudo: false
language: perl
perl:
  - blead
  - '5.26'
  - '5.24'
  - '5.22'
  - '5.20'
  - '5.18'
  - '5.16'
  - '5.14'
matrix:
  allow_failures:
    - perl: blead
env:
  global:
    - RELEASE_TESTING=1
    - AUTHOR_TESTING=1
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
  - cpanm -n App::af
  - af missing | cpanm
