---
abstract: 'Build or find premake5'
author:
  - 'José Joaquín Atria <jjatria@cpan.org>'
build_requires:
  Alien::Build: '0.32'
  Alien::Build::MM: '0.32'
  Capture::Tiny: '0'
  ExtUtils::MakeMaker: '6.52'
  Test2::V0: '0'
  Test::Alien: '0'
  perl: '5.006'
configure_requires:
  Alien::Build: '1.19'
  Alien::Build::MM: '0.32'
  ExtUtils::MakeMaker: '6.52'
  File::chdir: '0'
  perl: '5.006'
dynamic_config: 1
generated_by: 'Dist::Zilla version 6.010, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alien-premake5
provides:
  Alien::premake5:
    file: lib/Alien/premake5.pm
    version: '0.002'
requires:
  Alien::Base: '0'
  base: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/jjatria/Alien-premake5/issues
  repository: git://github.com/jjatria/Alien-premake5.git
version: '0.002'
x_alienfile:
  generated_by: 'Dist::Zilla::Plugin::AlienBuild version 0.24'
  requires:
    share:
      Archive::Zip: '0'
      Capture::Tiny: '0'
      HTML::LinkExtor: '0'
      HTTP::Tiny: '0.044'
      IO::Socket::SSL: '1.56'
      Net::SSLeay: '1.49'
      Path::Tiny: '0'
      Sort::Versions: '0'
      URI: '0'
      URI::Escape: '0'
    system:
      Capture::Tiny: '0'
x_serialization_backend: 'YAML::Tiny version 1.70'
